coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    project:
      Server:
        target: 70
        threshold: 5
        branches: null
        paths: "src/server/"
    patch: false
    changes: false
comment: false
