# Use Docker compose yml version 2
# https://docs.docker.com/compose/compose-file/#/version-2
version: '2'

# define our (services/images/containers/volumes/networks) which make up our swagger editor instance.

# Services
services:
  # SERVICE 1. Lets build our custom Swagger Editor image from Dockerfile
  # found in ./devel/docker/toolshedr-swagger-editor if needed.
  toolshedr-devel:

    container_name: toolshedr-sandbox

    # We define local name and version for our custom swagger-editor image so that we wont conflict with other images
    image: toolshedr-devel:1.1.10

    # If we did not find image:version on you computer then let's build it.
    # Docker expects to find 'Dockerfile' from defined path below
    build: ./devel/docker/images/toolshedr-swagger-editor

    # Let's map in-container web server port 80 to your computers port 8005
    # So after running (docker-compose up) You can access swagger-editor from http://localhost:8005
    # You are free to choose any free port instead of 8005.
    ports:
      - "8005:80"

    # Lets attach some volumes to web server
    volumes:
      # Lets override some Nginx configurations by just mounting our custom configuration file over the original.
      # where we have defined root path of our web server (inside of the container) and configure Nginx to pass requests
      # to php scripts over to our other php-fpm container to process because this image does not contain PHP.
      - ./devel/docker/images/toolshedr-swagger-editor/nginx/default.conf:/etc/nginx/conf.d/default.conf

      # We mount our swagger editor configuration file
      - ./devel/docker/images/toolshedr-swagger-editor/defaults.json:/swagger-web/config/defaults.json

      # Here we going to mount swagger-backend php scripts so that these can be served by Nginx web server.
      # Nginx is configured (see: ./devel/docker/images/toolshedr-swagger-editor/nginx/default.conf) to pass any requests
      # to php scripts to php-fpm (PHP FastCGI Process Manager our case living in another container "php7.1 container")
      # via toolshedr-network we defined here. Nginx uses internal TCP connection between these 2 containers
      # without having any effect on your computer.
      - ./devel/docker/images/toolshedr-swagger-editor/backend:/swagger-web/backend

      # And finally lets mount our docs to get api definitions yaml file
      - ./docs/api-definitions.yaml:/swagger-web/docs/api-definitions.yaml