version: '2'

services:

  toolshedr-devel:
    image: okramlabs/toolshedr-devel

    stdin_open: true
    tty: true
    privileged: true

    volumes:
      # API Definitions
      - ./docs/swagger.yaml:/var/www/toolshedr/public/swagger-editor/mount/swagger.yaml
      # Toolshed assets
      - ./public/toolshedr:/var/www/toolshedr/public/toolshedr
      # Mount Source
      - ./src:/var/www/toolshedr/src
      - ./package.json:/var/www/toolshedr/package.json
      - ./composer.json:/var/www/toolshedr/composer.json


    # Let's map in-container web server port 80 to your computers port 8005
    # So after running (docker-compose up) You can access swagger-editor from http://localhost:8005
    # You are free to choose any free port instead of 8005.
    ports:
      - "8010:80"
      - "2222:22"
