swagger: "2.0"
################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "1.0.0"
  title: API
# Your local or remote API server
host: localhost

# basePath prefixes all resource paths
basePath: /api/v1

schemes:
  - http  # should avoid to use it
  - https

# format of bodies a client can send (Content-Type)
consumes:
  - application/json

# format of the responses to the client (Accepts)
produces:
  - application/json

################################################################################
#                                  Security                                    #
################################################################################


################################################################################
#                                 Parameters                                   #
################################################################################


################################################################################
#                                    Paths                                     #
################################################################################
paths:

  ## Check connection status
  /status:
    get:
      description: Check connection status.
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Status'
        403:
          description: Forbidden! Invalid Toolshedr API KEY
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad Request X-Toolshedr-API-KEY header is missing
          schema:
            $ref: '#/definitions/Error'

    options:
      description: Same as GET but without response body
      responses:
        202:
          description: Accepted request headers are OK
          schema:
            $ref: '#/definitions/Status'
        403:
          description: Forbidden! Invalid Toolshedr API KEY
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad Request X-Toolshedr-API-KEY header is missing
          schema:
            $ref: '#/definitions/Error'


################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  Status:
    type: object
    properties:
      message:
        type: string
  Error:
    type: object
    properties:
      error:
        type: string